/*
* Essentialy the grammar of bytey
* helpful when parsing and writing bytey files
*
*/
// --- TOKENS --- //

// --- LEAFS --- //

// --- BYTEY OPCODE --- //

// SECTION INTERNAL
#define BY_SECTION_EOF 0x00

// SECTION DIRECTIVE
#define BY_DIRECTIVE_MATHIFY 0x0010
// SECTION PROGRAM
#define BY_PROGRAM_INSERT 0x0020
#define BY_PROGRAM_FILL 0x00021
// SECTION VALUE
#define BY_VALUE_VAR 0x0030
// SECTION CONTROL FLOW
#define BY_CONTROL_FLOW_CALL 0x0040
#define BY_CONTROL_FLOW_JMP 0x0041
#define BY_CONTROL_FLOW_RET 0x0042
#define BY_CONTROL_FLOW_INT 0x0043
#define BY_CONTROL_FLOW_SYSCALL 0x0044
#define BY_CONTROL_FLOW_IRET 0x0045
#define BY_CONTROL_FLOW_IHLT 0x0046
#define BY_CONTROL_FLOW_EHLT 0x0047
// SECTION OPERAND
#define BY_OPERAND_CMP 0x0050
#define BY_OPERAND_ADD 0x0051
#define BY_OPERAND_SUB 0x0052
#define BY_OPERAND_MUL 0x0053
#define BY_OPERAND_DIV 0x0054
#define BY_OPERAND_MOD 0x0055

// other
#define BY_OPCODE_TYPE uint16_t
#define BY_OPCODE_PRINT "%hu"

